spring.application.name=client

server.port=8001
server.address=0.0.0.0

spring.datasource.url=jdbc:h2:mem:clientdb;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

account.service.url=http://localhost:8000